version: '3.7'

services:
  searxng:
    image: searxng/searxng:latest
    container_name: spec-to-pack-searxng
    ports:
      - "8888:8080"
    volumes:
      - ./searxng/settings.yml:/etc/searxng/settings.yml:ro
      - ./searxng/uwsgi.ini:/etc/searxng/uwsgi.ini:ro
    environment:
      - SEARXNG_BASE_URL=http://localhost:8888/
    restart: unless-stopped
    networks:
      - searxng-network

networks:
  searxng-network:
    driver: bridge