use_default_settings: true

general:
  debug: false
  instance_name: "Spec-to-Pack Search"
  contact_url: false
  enable_metrics: false

search:
  safe_search: 1
  autocomplete: ""
  default_lang: "en"
  ban_time_on_fail: 5
  max_ban_time_on_fail: 120
  formats:
    - html
    - json

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "spec-to-pack-searxng-secret-key-change-in-production"
  base_url: "http://localhost:8888/"
  image_proxy: true
  http_protocol_version: "1.1"
  method: "GET"

# Enable specific engines for research quality
engines:
  - name: google
    engine: google
    disabled: false
    use_mobile_ui: false
  
  - name: bing  
    engine: bing
    disabled: false
    
  - name: duckduckgo
    engine: duckduckgo
    disabled: false
    
  - name: startpage
    engine: startpage
    disabled: false
    
  - name: wikipedia
    engine: wikipedia
    disabled: false
    categories: [general, it]
    
  - name: github
    engine: github
    disabled: false
    categories: [it]
    
  - name: stackoverflow
    engine: stackoverflow
    disabled: false
    categories: [it]